### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by davidchambers** [masaeedu/sanctuary_profiling#1]
@masaeedu, would you mind adding a very short readme describing how to run this?

**Comment by masaeedu** [comment]
@davidchambers It consists of little more than that JS file and some npm tasks I'm afraid. I've added a `README.md` file. I was doing the disabled cloning comparison by just directly editing `updateTypeVarMap` in `node_modules/sanctuary-def/index.js`.

**Comment by davidchambers** [comment]
Very helpful. Thank you. :)
